// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG7311.FarmProducts.ST10153536.Data;

#nullable disable

namespace PROG7311.FarmProducts.ST10153536.Migrations
{
    [DbContext(typeof(PROG7311FarmProductsST10153536Context))]
    [Migration("20230605023257_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
       

    }
}
