// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG7311.FarmProducts.ST10153536.Data;

#nullable disable

namespace PROG7311.FarmProducts.ST10153536.Migrations
{
    
    
}
